### ISSUE TITLE
`goto` used as identifier and preceded by `then` errors with `compiler assert failed`

### ISSUE THREAD

**Issue by Kan18** [cc-tweaked/Cobalt#84]
The following code (tested on CC:T 1.109.2 via copy-cat) fails to compile, returning an error message of `compiler assert failed`:
```lua
local function goto(x) print(x) end 
if true then goto("Hello") end
```
This breaks compatibility with at least one older program which used `goto` as an identifier. (Screenshot:
<img width="941" alt="image" src="https://github.com/cc-tweaked/Cobalt/assets/24967425/b204d3f0-81f7-41e1-9df9-5e8dcf12b1e8">
)

**Comment by SquidDev** [comment]
Thanks for the report!

A minimal reproduction case here appears to be `if true then goto() end`. I suspect this is an issue with the [jump threading the compiler tries to do](https://github.com/cc-tweaked/Cobalt/blob/6d5253850c8cccca05a96fdaf645acc4eb1ea2fa/src/main/java/org/squiddev/cobalt/compiler/Parser.java#L1234) - will take a look.
