### ISSUE TITLE
Varargs not accepting nil values

### ISSUE THREAD

**Issue by tehbiga** [cc-tweaked/Cobalt#85]
Sorry if this should instead be in the cc-tweaked repo!

When using the following function on Lua 5.1.4 and Cobalt through CC: Tweaked I get different behavior. Vararg values beyond and including the first `nil` are unexpectedly dropped.

_Test function:_

```lua
function test(...) print(#{ ... }) end
```

_Lua 5.1.4 output:_

```
ILUA: Lua 5.1.4  Copyright (C) 1994-2008 Lua.org, PUC-Rio
"quit" to end
> function test(...) print(#{ ... }) end
> test()
0
> test(1)
1
> test(1, 2)
2
> test(nil, 1, 2)
3
> test(1, nil, 2)
3
```

_CC: Tweaked output:_

![Image of computer output](https://i.imgur.com/xxsCKCl.png)

**Comment by Wojbie** [comment]
Hey! What you are experiencing is less vararg dropping stuff on nils (as you can see below its still passed) and more odd stuff related to table length and # calculations in Cobalt.

Related to issues: #51 #62 and #63 . Possibly #61 too?

### Sidenote:

Just to visualize what i mean and to re-validate your test in Lua 5.2 as Cobalt recently moved to 5.2
```
function test(...) print(#{ ... }, ...) end
test()
test(1)
test(1, 2)
test(nil, 1, 2)
test(1, nil, 2)
```
![image](https://github.com/cc-tweaked/Cobalt/assets/5893536/2b66196d-36ec-4ccd-9e86-15e5931a1679)
![obraz](https://github.com/cc-tweaked/Cobalt/assets/5893536/3d2a0b31-3263-4976-8f69-ca4dd89e47e2)

**Comment by tehbiga** [comment]
Wow @SquidDev already patched it, crazy!

Thanks everyone!

**Comment by SquidDev** [comment]
Thanks for the report! Hah, that was a fun one - I knew our implementation of `SETLIST` was the issue here, but hadn't realised the difference in `luaH_resizearray` would also be an issue.

That all said, I would recommend using `table.pack(...)` rather than `{...}` when dealing with varargs that contain nils. These sorts of lists are incredibly brittle, and so doing other operations on the table will cause their length to "reset".

For example:

```lua
> a = (function(...) return { ... } end)(nil, 2)
> #a
2
> a.n = 1 -- Rehash the table, causing the array part to shrink
> #a
0
```

**Comment by tehbiga** [comment]
@SquidDev so my test was invalid-ish too. I shortened the test to try and reduce what you had to read, but in actually what I was running into was that I stored varargs in a table then later unpacked it into a pcall. It looks like you got there in the end!

**Comment by SquidDev** [comment]
Yeah, in those cases you definitely want to be using `table.pack`/`table.unpack`. For instance, this is how we [pass events between coroutines](https://github.com/cc-tweaked/CC-Tweaked/blob/1d6e3f4fc0bff06112a6437f598076f25397b648/projects/core/src/main/resources/data/computercraft/lua/rom/modules/main/cc/internal/exception.lua#L48-L50).
